#!/usr/bin/env sh
# entrypoint-scheduler.sh — starts the scheduler.
# Secrets are generated by the bootstrap container; the volume is read-only here.
set -eu

SECRETS_DIR="${SECRETS_DIR:-/runtime/secrets}"

log() { printf '[entrypoint-scheduler] %s\n' "$1" >&2; }

if [ ! -f "$SECRETS_DIR/db_apppassword.txt" ]; then
  log "ERROR: secrets not found — did the bootstrap container run?"
  exit 1
fi

log "Starting scheduler..."
exec /app/bin/scheduler "$@"
