#!/usr/bin/env sh
# entrypoint-worker.sh — starts the background worker.
# Secrets are generated by the bootstrap container; the volume is read-only here.
set -eu

SECRETS_DIR="${SECRETS_DIR:-/runtime/secrets}"

log() { printf '[entrypoint-worker] %s\n' "$1" >&2; }

if [ ! -f "$SECRETS_DIR/db_apppassword.txt" ]; then
  log "ERROR: secrets not found — did the bootstrap container run?"
  exit 1
fi

log "Starting worker..."
exec /app/bin/worker "$@"
