#!/usr/bin/env sh
# entrypoint-api.sh — runs init_db, then starts the API server.
# Secrets are generated by the bootstrap container (docker-compose depends_on);
# this entrypoint does NOT re-run bootstrap because the secrets volume is
# mounted read-only in the api/worker/scheduler services.
set -eu

SECRETS_DIR="${SECRETS_DIR:-/runtime/secrets}"

log() { printf '[entrypoint-api] %s\n' "$1" >&2; }

# Verify secrets were generated by the bootstrap container.
if [ ! -f "$SECRETS_DIR/db_apppassword.txt" ]; then
  log "ERROR: secrets not found at $SECRETS_DIR — did the bootstrap container run?"
  exit 1
fi

# Run database init (idempotent — creates user/db/extensions, applies
# migrations and seeds).
log "Running database init..."
SECRETS_DIR="$SECRETS_DIR" /app/init_db.sh

log "Starting API server..."
exec /app/bin/api "$@"
